apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-configmap
  # namespace: challenge
data:
  DB_HOST: postgresql://posfiap:posfiap2@postgres-service:5432/posfiap
  PORT: "8080"
  ID_USUARIO_MP: usuario
  ID_EXTERNO_CAIXA: cx01